rules:
  indent: [2, 2, {SwitchCase: 1}]
  comma-dangle: [0, always-multiline]
  quotes: [2, single, avoid-escape]
  linebreak-style: [1, unix]
  semi: [1, never]
env:
  es6: true
  browser: true
extends: 'eslint:recommended'
ecmaFeatures:
  experimentalObjectRestSpread: true
  modules: true

plugins:
  - html
